use super::super::*;
use super::parsing::*;

pub(super) fn parse_ls(args: &[String]) -> Option<SafeCommandParse> {
    input_parse(
        parse_options(
            args,
            &grammar(
                "aAbBcCdDFghHiIklmnNopqQrRsStuUvwxX1",
                "",
                &[
                    "--all",
                    "--almost-all",
                    "--author",
                    "--escape",
                    "--ignore-backups",
                    "--classify",
                    "--color",
                    "--directory",
                    "--dired",
                    "--file-type",
                    "--full-time",
                    "--group-directories-first",
                    "--hide-control-chars",
                    "--human-readable",
                    "--inode",
                    "--literal",
                    "--numeric-uid-gid",
                    "--quote-name",
                    "--reverse",
                    "--recursive",
                    "--size",
                    "--zero",
                ],
                &[
                    "--block-size",
                    "--format",
                    "--hide",
                    "--ignore",
                    "--indicator-style",
                    "--quoting-style",
                    "--sort",
                    "--time",
                    "--time-style",
                    "--hyperlink",
                    "--width",
                ],
            ),
        )?,
        SafeShellPresentation::List,
        0,
        None,
        true,
    )
}
